name: tumbuh_iman
description:  "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:  ^1.0.8

  # Network
  dio: ^5.4.0
  retrofit: ^4.9.0
  json_annotation: ^4.9.0

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Code Generation
  freezed_annotation: ^3.0.0

  # Routing
  go_router:  ^13.0.0

  # Local Storage
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  retrofit_generator: ^10.2.1
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  injectable_generator: ^2.4.1
  freezed: ^3.0.0
  drift_dev: ^2.14.0

flutter:

  uses-material-design:  true